#!/usr/bin/env bash

# used to export environment variables in Travis for server setup
export POSTGRES_USER=${POSTGRES_USER}
export POSTGRES_DB=${POSTGRES_DB}
export POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
export SECRET_KEY=${SECRET_KEY}
export CSRF_SESSION_KEY=${CSRF_SESSION_KEY}
export SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT}
export ADMIN_EMAIL_1=${ADMIN_EMAIL_1}
export FLASK_CONFIG=${FLASK_CONFIG}
export CELERY_BROKER_URL=${CELERY_BROKER_URL}
export CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
export MAIL_USERNAME=${MAIL_USERNAME}
export MAIL_PASSWORD=${MAIL_PASSWORD}
export MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER}
export REDIS_SERVER=${REDIS_SERVER}
export REDIS_PORT=${REDIS_PORT}
export REDIS_DB=${REDIS_DB}
