#!/usr/bin/env bash

touch .env

echo POSTGRES_USER=${POSTGRES_USER} >> .env >> .env
echo POSTGRES_DB=${POSTGRES_DB} >> .env
echo POSTGRES_PASSWORD=${POSTGRES_PASSWORD} >> .env
echo SECRET_KEY=${SECRET_KEY} >> .env
echo CSRF_SESSION_KEY=${CSRF_SESSION_KEY} >> .env
echo SECURITY_PASSWORD_SALT=${SECURITY_PASSWORD_SALT} >> .env
echo ADMIN_EMAIL_1=${ADMIN_EMAIL_1} >> .env
echo FLASK_CONFIG=${FLASK_CONFIG} >> .env
echo CELERY_BROKER_URL=${CELERY_BROKER_URL} >> .env
echo CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND} >> .env
echo MAIL_USERNAME=${MAIL_USERNAME} >> .env
echo MAIL_PASSWORD=${MAIL_PASSWORD} >> .env
echo MAIL_DEFAULT_SENDER=${MAIL_DEFAULT_SENDER} >> .env
echo REDIS_SERVER=${REDIS_SERVER} >> .env
echo REDIS_PORT=${REDIS_PORT} >> .env
echo REDIS_DB=${REDIS_DB} >> .env
