# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdirectory', '0004_auto_20160912_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='bio',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='person',
            name='responsibilities',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
