# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teamdirectory', '0006_auto_20160912_2020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='github_url',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='linkedin_url',
            new_name='linkedin',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='twitter_url',
            new_name='twitter',
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
