# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=500)),
            ],
        ),
    ]
