# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-10 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdirectory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='person',
            name='github_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Lusina', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
