# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdirectory', '0002_auto_20160910_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
