# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdirectory', '0003_person_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
