# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamdirectory', '0005_auto_20160912_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='slug',
            field=models.SlugField(blank=True, max_length=1000),
        ),
    ]
